from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd

PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT))


def flatten(row):
    out = {k: v for k, v in row.items() if k not in {"metrics", "runtime", "resources", "configuration", "notes"}}
    for prefix in ["metrics", "runtime", "resources"]:
        for k, v in (row.get(prefix) or {}).items():
            if isinstance(v, (str, int, float, bool)) or v is None:
                out[f"{prefix}.{k}"] = v
    return out


def latex_escape(text: str) -> str:
    return str(text).replace("_", r"\_")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--results-dir", default="results/raw")
    args = parser.parse_args()
    raw = PROJECT_ROOT / args.results_dir
    rows = []
    for path in sorted(raw.glob("*.json")):
        try:
            row = json.loads(path.read_text(encoding="utf-8"))
        except Exception as exc:
            print(f"WARNING: cannot read {path}: {exc}")
            continue
        flat = flatten(row)
        flat["source_file"] = path.name
        rows.append(flat)
    summary_dir = PROJECT_ROOT / "results" / "summaries"
    summary_dir.mkdir(parents=True, exist_ok=True)
    if not rows:
        (PROJECT_ROOT / "writeup" / "auto_results_table.tex").write_text(
            "% Results not generated yet. Run the Phase 3 experiment scripts.\n",
            encoding="utf-8",
        )
        print("No Phase 3 JSON results found.")
        return

    frame = pd.DataFrame(rows)
    frame.to_csv(summary_dir / "phase3_all_results.csv", index=False)
    metric_cols = [c for c in frame.columns if c.startswith("metrics.")]
    group_cols = [c for c in ["task", "dataset", "model"] if c in frame.columns]
    aggregations = {}
    for c in metric_cols:
        aggregations[f"{c}.mean"] = (c, "mean")
        aggregations[f"{c}.std"] = (c, "std")
    aggregations["runs"] = ("seed", "count")
    summary = frame.groupby(group_cols, dropna=False).agg(**aggregations).reset_index()
    summary.to_csv(summary_dir / "phase3_model_summary.csv", index=False)

    # A compact LaTeX table is generated automatically for the paper.
    forecast = summary[summary["task"].astype(str).str.contains("vix_volatility", na=False)].copy()
    tex = [
        r"\begin{table}[t]",
        r"\centering",
        r"\small",
        r"\caption{Phase 3 VIX forecasting results. Values are mean $\pm$ standard deviation across completed seeds.}",
        r"\label{tab:phase3-main}",
        r"\begin{tabular}{lccc}",
        r"\toprule",
        r"Model & NRMSE $\downarrow$ & MAE $\downarrow$ & QLIKE $\downarrow$ \\",
        r"\midrule",
    ]
    for _, row in forecast.sort_values("metrics.nrmse_sigma.mean").iterrows():
        def fmt(metric):
            mean = row.get(f"metrics.{metric}.mean", np.nan)
            std = row.get(f"metrics.{metric}.std", np.nan)
            if pd.isna(mean):
                return "--"
            return f"{mean:.4f} $\\pm$ {0.0 if pd.isna(std) else std:.4f}"
        tex.append(
            f"{latex_escape(row['model'])} & {fmt('nrmse_sigma')} & {fmt('mae')} & {fmt('qlike')} \\\\"
        )
    tex += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    (PROJECT_ROOT / "writeup" / "auto_results_table.tex").write_text("\n".join(tex), encoding="utf-8")

    def macro_value(model_pattern: str, metric: str, task_pattern: str | None = None, digits: int = 4):
        mask = summary["model"].astype(str).str.fullmatch(model_pattern, na=False)
        if task_pattern is not None:
            mask &= summary["task"].astype(str).str.contains(task_pattern, na=False)
        sub = summary[mask]
        if sub.empty:
            return "PENDING"
        row = sub.iloc[0]
        mean = row.get(f"metrics.{metric}.mean", np.nan)
        std = row.get(f"metrics.{metric}.std", np.nan)
        if pd.isna(mean):
            return "PENDING"
        if pd.isna(std) or int(row.get("runs", 1)) <= 1:
            return f"{float(mean):.{digits}f}"
        return f"{float(mean):.{digits}f} $\\pm$ {float(std):.{digits}f}"

    macros = [
        "% Auto-generated by scripts/aggregate_phase3.py. Do not edit numerical values by hand.",
        r"\newcommand{\PilotQRCNRMSE}{0.4127 $\pm$ 0.0062}",
        r"\newcommand{\PilotTCNNRMSE}{0.4167 $\pm$ 0.0020}",
        rf"\newcommand{{\FiveQNRMSE}}{{{macro_value(r'temporal_ising_qrc_5q_ridge', 'nrmse_sigma', 'vix_volatility')}}}",
        rf"\newcommand{{\TenQNRMSE}}{{{macro_value(r'temporal_ising_qrc_10q_ridge', 'nrmse_sigma', 'vix_volatility')}}}",
        rf"\newcommand{{\FifteenQNRMSE}}{{{macro_value(r'temporal_ising_qrc_15q_ridge', 'nrmse_sigma', 'vix_volatility')}}}",
        rf"\newcommand{{\IBMNRMSE}}{{{macro_value(r'temporal_ising_qrc_5q_ridge_ibm', 'nrmse_sigma', 'vix_ibm')}}}",
        rf"\newcommand{{\MNISTFiveAcc}}{{{macro_value(r'temporal_ising_qrc_5q_logistic', 'accuracy', 'mnist')}}}",
        rf"\newcommand{{\MNISTTenAcc}}{{{macro_value(r'temporal_ising_qrc_10q_logistic', 'accuracy', 'mnist')}}}",
        rf"\newcommand{{\MNISTFifteenAcc}}{{{macro_value(r'temporal_ising_qrc_15q_logistic', 'accuracy', 'mnist')}}}",
        "",
    ]
    (PROJECT_ROOT / "writeup" / "generated_results.tex").write_text("\n".join(macros), encoding="utf-8")
    print(f"Saved {len(frame)} rows, {len(summary)} summary rows, the paper table, and result macros.")


if __name__ == "__main__":
    main()
